# Generated by Django 2.1.3 on 2018-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
