# Generated by Django 2.1.3 on 2018-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactions_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
