# Generated by Django 2.1.3 on 2018-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181118_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
