# Generated by Django 2.1.3 on 2018-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20181123_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='plan',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
