# Generated by Django 2.1.3 on 2018-12-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transactions_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transactionType',
            new_name='duration',
        ),
    ]
