# Generated by Django 2.1.3 on 2018-11-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccount',
            old_name='credentialsName',
            new_name='amazon_email',
        ),
        migrations.RenameField(
            model_name='selleraccount',
            old_name='marketPlace',
            new_name='amazon_password',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='mwsAuthToken',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='sellerId',
        ),
    ]
