# Generated by Django 2.1.3 on 2018-11-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_seller', '0002_auto_20181108_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraccount',
            old_name='amazon_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='selleraccount',
            old_name='amazon_password',
            new_name='password',
        ),
    ]
