# Generated by Django 2.1.3 on 2018-11-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_auto_20181111_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingID', models.CharField(max_length=50)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='trackingdetails',
            name='trackingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.TrackingID'),
        ),
    ]
