# Generated by Django 2.1.3 on 2018-11-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_trackingid'),
        ('tracking', '0002_auto_20181111_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingid',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='trackingdetails',
            name='trackingID',
        ),
        migrations.AddField(
            model_name='trackingdetails',
            name='orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrackingID',
        ),
    ]
