# Generated by Django 2.1.3 on 2018-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderData', models.CharField(max_length=120)),
                ('orderNumber', models.CharField(max_length=120)),
                ('orderStatus', models.CharField(max_length=120)),
                ('shippingAddress', models.TextField(max_length=120)),
                ('paymentMethod', models.TextField(max_length=120)),
                ('productName', models.CharField(max_length=120)),
            ],
        ),
    ]
