# Generated by Django 2.1.3 on 2018-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181111_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trackingID',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
