# Generated by Django 2.1.3 on 2018-12-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paymentMethod',
        ),
    ]
